{
  config,
  lib,
  ...
}:
let
  inherit (lib) mkOption mkIf types;
  cfg = config.melinoe.services.ssh;

  knownHostLine =
    entry:
    "${lib.optionalString entry.certAuthority "@cert-authority "}${
      lib.concatStringsSep "," entry.hosts
    } ${entry.publicKey}";
in
{
  options.melinoe.services.ssh = {
    userCA = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = ''
        Public key of the SSH user certificate authority trusted for logging
        into this machine (the contents of a CA `.pub` file). When set, this
        is installed to /etc/ssh/ssh-user-ca.pub and wired up as sshd's
        TrustedUserCAKeys, so any user certificate signed by this CA is
        accepted for login.

        Note: per-user authorized keys are unaffected by this and are still
        set via users.users.<name>.openssh.authorizedKeys.
      '';
    };

    hostCert = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = ''
        Filesystem path to this host's own SSH host certificate (the signed
        counterpart of one of its host keys), installed as sshd's
        HostCertificate. This is expected to already exist on disk - e.g.
        provisioned/rotated out-of-band by mel-ssh-host-ca - rather than be
        generated by Nix.
      '';
    };

    knownHosts = mkOption {
      type = types.listOf (
        types.submodule {
          options = {
            hosts = mkOption {
              type = types.listOf types.str;
              description = "Hostnames/IP patterns (as used in ssh_known_hosts) this entry applies to.";
            };
            publicKey = mkOption {
              type = types.str;
              description = "The public key for this entry - an individual host key, or a CA key when certAuthority is true.";
            };
            certAuthority = mkOption {
              type = types.bool;
              default = false;
              description = ''
                Whether publicKey is a certificate authority that should be
                trusted for signing host certificates for all of `hosts`,
                rather than being one specific host's own key.
              '';
            };
          };
        }
      );
      default = [ ];
      description = "Entries rendered into /etc/ssh/ssh_known_hosts.";
    };
  };

  config = {
    services.openssh.settings.TrustedUserCAKeys = mkIf (cfg.userCA != null) "/etc/ssh/ssh-user-ca.pub";
    environment.etc."ssh/ssh-user-ca.pub" = mkIf (cfg.userCA != null) {
      text = cfg.userCA;
      mode = "0644";
    };

    services.openssh.settings.HostCertificate = mkIf (cfg.hostCert != null) cfg.hostCert;

    environment.etc."ssh/ssh_known_hosts" = mkIf (cfg.knownHosts != [ ]) {
      text = lib.concatMapStringsSep "\n" knownHostLine cfg.knownHosts + "\n";
    };
  };
}
