{
  config,
  lib,
  ...
}:
let
  inherit (lib) mkOption mkIf types;
  cfg = config.melinoe.services.ssh;

  knownHostLine =
    entry:
    "${lib.optionalString entry.certAuthority "@cert-authority "}${
      lib.concatStringsSep "," entry.hosts
    } ${entry.publicKey}";
in
{
  options.melinoe.services.ssh = {
    enabled = mkOption {
      type = types.bool;
      default = false;
      description = "Whether to enable and configure sshd on this host. All other melinoe.services.ssh.* options are no-ops unless this is true.";
    };

    ports = mkOption {
      type = types.listOf types.port;
      default = [ 22 ];
      description = "Ports sshd listens on.";
    };

    passwordAuthentication = mkOption {
      type = types.bool;
      default = false;
      description = "Whether to allow password authentication.";
    };

    kbdInteractiveAuthentication = mkOption {
      type = types.bool;
      default = false;
      description = "Whether to allow keyboard-interactive authentication.";
    };

    acceptEnv = mkOption {
      type = types.listOf types.str;
      default = [ ];
      description = "Client environment variable names to accept (sshd's AcceptEnv).";
    };

    fwOpenPorts = mkOption {
      type = types.either types.bool (types.listOf types.port);
      default = false;
      description = ''
        Whether (and which) sshd ports to add to
        melinoe.node.networking.openPorts.tcp. `true` adds all of `ports`;
        a list adds just those ports instead, for e.g. firewalling off an
        internal-only listener while still exposing 22.
      '';
    };

    userCA = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = ''
        Public key of the SSH user certificate authority trusted for logging
        into this machine (the contents of a CA `.pub` file). When set, this
        is installed to /etc/ssh/ssh-user-ca.pub and wired up as sshd's
        TrustedUserCAKeys, so any user certificate signed by this CA is
        accepted for login.

        Note: per-user authorized keys are unaffected by this and are still
        set via users.users.<name>.openssh.authorizedKeys.
      '';
    };

    hostCert = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = ''
        Filesystem path to this host's own SSH host certificate (the signed
        counterpart of one of its host keys), installed as sshd's
        HostCertificate. This is expected to already exist on disk - e.g.
        provisioned/rotated out-of-band by mel-ssh-host-ca - rather than be
        generated by Nix.
      '';
    };

    hostCA = mkOption {
      type = types.nullOr types.str;
      default = null;
      description = ''
        Public key of the SSH host certificate authority that signed this
        host's hostCert (the contents of a CA `.pub` file), published to
        /etc/ssh/ssh-host-ca.pub for reference by other tooling (e.g.
        mel-ssh-host-ca). This is purely informational - it does not by
        itself establish any trust, since sshd/ssh only ever act on the
        *-ca.pub files that TrustedUserCAKeys and ssh_known_hosts actually
        point at. Note this is usually the same key as any certAuthority
        entry in knownHosts, since that entry is what makes clients actually
        trust it - hostCA just re-publishes it under a well-known path.
      '';
    };

    knownHosts = mkOption {
      type = types.listOf (
        types.submodule {
          options = {
            hosts = mkOption {
              type = types.listOf types.str;
              description = "Hostnames/IP patterns (as used in ssh_known_hosts) this entry applies to.";
            };
            publicKey = mkOption {
              type = types.str;
              description = "The public key for this entry - an individual host key, or a CA key when certAuthority is true.";
            };
            certAuthority = mkOption {
              type = types.bool;
              default = false;
              description = ''
                Whether publicKey is a certificate authority that should be
                trusted for signing host certificates for all of `hosts`,
                rather than being one specific host's own key.
              '';
            };
          };
        }
      );
      default = [ ];
      description = "Entries rendered into /etc/ssh/ssh_known_hosts.";
    };
  };

  config = mkIf cfg.enabled {
    services.openssh.enable = true;
    services.openssh.ports = cfg.ports;
    services.openssh.settings.PasswordAuthentication = cfg.passwordAuthentication;
    services.openssh.settings.KbdInteractiveAuthentication = cfg.kbdInteractiveAuthentication;
    services.openssh.extraConfig = mkIf (cfg.acceptEnv != [ ]) (
      "AcceptEnv ${lib.concatStringsSep " " cfg.acceptEnv}"
    );

    melinoe.node.networking.openPorts.tcp =
      if cfg.fwOpenPorts == true then
        cfg.ports
      else if cfg.fwOpenPorts == false then
        [ ]
      else
        cfg.fwOpenPorts;

    services.openssh.settings.TrustedUserCAKeys = mkIf (cfg.userCA != null) "/etc/ssh/ssh-user-ca.pub";
    environment.etc."ssh/ssh-user-ca.pub" = mkIf (cfg.userCA != null) {
      text = cfg.userCA;
      mode = "0644";
    };

    services.openssh.settings.HostCertificate = mkIf (cfg.hostCert != null) cfg.hostCert;

    environment.etc."ssh/ssh-host-ca.pub" = mkIf (cfg.hostCA != null) {
      text = cfg.hostCA;
      mode = "0644";
    };

    environment.etc."ssh/ssh_known_hosts" = mkIf (cfg.knownHosts != [ ]) {
      text = lib.concatMapStringsSep "\n" knownHostLine cfg.knownHosts + "\n";
    };
  };
}
