#ifndef _MELNODE_GENL_H
#define _MELNODE_GENL_H

#define MELNODE_GENL_NAME	"melnode"
#define MELNODE_GENL_VERSION	4

enum melnode_genl_cmd {
	MELNODE_CMD_UNSPEC = 0,
	MELNODE_CMD_DEVICE_SET = 1,
	MELNODE_CMD_STATS_GET = 2,
	MELNODE_CMD_LINK_SET = 3,
	MELNODE_CMD_LINK_DEL = 4,
	MELNODE_CMD_LINK_GET = 5,
	MELNODE_CMD_ROUTE_SET = 6,
	MELNODE_CMD_ROUTE_GET = 7,
	MELNODE_CMD_INJECT = 8,
	MELNODE_CMD_TUN_SET = 9,
	MELNODE_CMD_TUN_DEL = 10,
	MELNODE_CMD_TUN_GET = 11,
	MELNODE_CMD_PUNT = 12,
};

enum melnode_genl_attr {
	MELNODE_A_UNSPEC = 0,
	MELNODE_A_PAD = 1,
	MELNODE_A_LOCAL_ID = 2,
	MELNODE_A_PRIVATE_KEY = 3,
	MELNODE_A_PUBLIC_KEY = 4,
	MELNODE_A_LISTEN_PORT = 5,
	MELNODE_A_FWMARK = 6,
	MELNODE_A_MTU = 7,
	MELNODE_A_PEER_ID = 8,
	MELNODE_A_ENDPOINT = 9,
	MELNODE_A_LAST_HANDSHAKE = 10,
	MELNODE_A_TX_BYTES = 11,
	MELNODE_A_RX_BYTES = 12,
	MELNODE_A_TUN_NAME = 13,
	MELNODE_A_TUN_IFINDEX = 14,
	MELNODE_A_ROUTES = 15,
	MELNODE_A_ROUTE = 16,
	MELNODE_A_ROUTE_DST = 17,
	MELNODE_A_ROUTE_NEXTHOP = 18,
	MELNODE_A_STAT_ID = 19,
	MELNODE_A_STAT_VALUE = 20,
	MELNODE_A_PKT_LINK = 21,
	MELNODE_A_PKT_PROTO = 22,
	MELNODE_A_PKT_SRC = 23,
	MELNODE_A_PKT_DST = 24,
	MELNODE_A_PKT_TTL = 25,
	MELNODE_A_PKT_DATA = 26,
};

enum melnode_stat {
	MELNODE_STAT_PUNT_SENT = 1,
	MELNODE_STAT_PUNT_DROPPED = 2,
	MELNODE_STAT_INJECT_SENT = 3,
	MELNODE_STAT_INJECT_DROPPED = 4,
	MELNODE_STAT_RX_NO_ROUTE = 5,
	MELNODE_STAT_RX_TTL_EXPIRED = 6,
	MELNODE_STAT_RX_NO_TUN = 7,
	MELNODE_STAT_RX_TUN_FULL = 8,
	MELNODE_STAT_RX_BAD_PACKET = 9,
	MELNODE_STAT_TX_NO_ROUTE = 10,
	MELNODE_STAT_TX_QUEUE_FULL = 11,
	MELNODE_STAT_RX_QUEUE_FULL = 12,
};

#endif
