#ifndef _MELNODE_GENL_H
#define _MELNODE_GENL_H

#define MELNODE_GENL_NAME	"melnode"
#define MELNODE_GENL_VERSION	3

enum melnode_genl_cmd {
	MELNODE_CMD_UNSPEC = 0,
	MELNODE_CMD_HELLO = 1,
	MELNODE_CMD_ATTACH = 2,
	MELNODE_CMD_DEVICE_SET = 3,
	MELNODE_CMD_DEVICE_DEL = 4,
	MELNODE_CMD_STATS_GET = 5,
	MELNODE_CMD_LINK_ADD = 6,
	MELNODE_CMD_LINK_DEL = 7,
	MELNODE_CMD_LINK_GET = 8,
	MELNODE_CMD_TUN_CREATE = 9,
	MELNODE_CMD_TUN_START = 10,
	MELNODE_CMD_TUN_DESTROY = 11,
	MELNODE_CMD_TUN_GET = 12,
	MELNODE_CMD_ROUTE_SET = 13,
	MELNODE_CMD_ROUTE_DEL = 14,
	MELNODE_CMD_ROUTE_GET = 15,
	MELNODE_CMD_PUNT = 16,
	MELNODE_CMD_INJECT = 17,
	MELNODE_CMD_EVENT = 18,

	MELNODE_CMD_X_QUIT = 128,
};

enum melnode_genl_attr {
	MELNODE_A_UNSPEC = 0,
	MELNODE_A_PAD = 1,
	MELNODE_A_API_VERSION = 2,
	MELNODE_A_PID = 3,
	MELNODE_A_CONFIGURED = 4,
	MELNODE_A_LOCAL_ID = 5,
	MELNODE_A_PRIVATE_KEY = 6,
	MELNODE_A_PUBLIC_KEY = 7,
	MELNODE_A_LISTEN_PORT = 8,
	MELNODE_A_FWMARK = 9,
	MELNODE_A_MTU = 10,
	MELNODE_A_PEER_ID = 11,
	MELNODE_A_ENDPOINT = 12,
	MELNODE_A_LAST_HANDSHAKE = 13,
	MELNODE_A_TX_BYTES = 14,
	MELNODE_A_RX_BYTES = 15,
	MELNODE_A_TUN_NAME = 16,
	MELNODE_A_TUN_STARTED = 17,
	MELNODE_A_ROUTE_DST = 18,
	MELNODE_A_ROUTE_NEXTHOP = 19,
	MELNODE_A_STAT_ID = 20,
	MELNODE_A_STAT_VALUE = 21,
	MELNODE_A_PKT_LINK = 22,
	MELNODE_A_PKT_PROTO = 23,
	MELNODE_A_PKT_SRC = 24,
	MELNODE_A_PKT_DST = 25,
	MELNODE_A_PKT_TTL = 26,
	MELNODE_A_PKT_DATA = 27,
	MELNODE_A_EVT_KIND = 28,
	MELNODE_A_EVT_TIME = 29,
};

enum melnode_event_kind {
	MELNODE_EVENT_LINK_HANDSHAKE = 1,
};

enum melnode_stat {
	MELNODE_STAT_PUNT_SENT = 1,
	MELNODE_STAT_PUNT_DROPPED = 2,
	MELNODE_STAT_INJECT_SENT = 3,
	MELNODE_STAT_INJECT_DROPPED = 4,
	MELNODE_STAT_RX_NO_ROUTE = 5,
	MELNODE_STAT_RX_TTL_EXPIRED = 6,
	MELNODE_STAT_RX_NO_TUN = 7,
	MELNODE_STAT_RX_TUN_FULL = 8,
	MELNODE_STAT_RX_BAD_PACKET = 9,
	MELNODE_STAT_TX_NO_ROUTE = 10,
	MELNODE_STAT_TX_QUEUE_FULL = 11,
	MELNODE_STAT_EVENTS_DROPPED = 12,
	MELNODE_STAT_RX_QUEUE_FULL = 13,
};

#endif
