#!/usr/bin/env python3
"""melnode-helper: the glue between melnode and the rest of the host.

melnode itself only builds the mesh and creates one `node-<peerid>` tun per
reachable node. Everything the old melinoe-route daemon did *around* those
tuns lives here instead:

  hook-create <peerid> <ifname>
      melnode tunCreateHookBin: set up per-node policy routing (fwmark and
      table `table_base + peerid`, default route via the tun) and register
      the tun in the nft conntrack-pinning set/map.

  hook-destroy <peerid> <ifname>
      melnode tunDestroyHookBin: undo the above (runs after the tun is gone).

  daemon
      Long-running. Every tick it:
        * advertises this node's prefixes (routes on vm-* interfaces,
          public IPs, extraRoutes) to melnode's control socket, and
          withdraws them when they disappear;
        * heals per-tun state (rules/routes/nft entries) that the hooks set
          up but something else removed, e.g. an nftables reload flushing
          the runtime sets, and garbage-collects state for vanished tuns.

Config is a JSON file (--config), generated by modules/melinoe-vpn.nix.
Only the standard library, `ip` and `nft` (on PATH) are used.
"""

from __future__ import annotations

import argparse
import http.client
import ipaddress
import json
import logging
import os
import signal
import socket
import subprocess
import sys
import threading
from dataclasses import dataclass, field

log = logging.getLogger("melnode-helper")

MAX_PEER_ID = 255

# Same protocol number melnode tags its own kernel routes with
# (routeProtocolMelnode in kernelroutes.go): `ip route show proto 198`.
ROUTE_PROTO = "198"


# --------------------------------------------------------------------------
# Config
# --------------------------------------------------------------------------


@dataclass
class Config:
    node_id: int
    table_base: int
    tun_prefix: str
    control_socket: str
    pub_ips: list[str]
    extra_routes: list[str]
    vm_ifaces: list[str]
    nft_family: str = "inet"
    nft_table: str = "mangle"
    nft_mark_set: str = "melinoe_peer_marks"
    nft_iface_map: str = "melinoe_peer_ifaces"
    poll_interval: float = 2.0
    full_resync_ticks: int = 5

    @staticmethod
    def load(path: str) -> "Config":
        with open(path) as f:
            return Config(**json.load(f))

    def table(self, peer_id: int) -> int:
        return self.table_base + peer_id

    def peer_id_of(self, ifname: str) -> int | None:
        """`node-4` -> 4; anything that isn't one of our tuns -> None."""
        if not ifname.startswith(self.tun_prefix):
            return None
        rest = ifname[len(self.tun_prefix):]
        if not rest.isdigit():
            return None
        pid = int(rest)
        return pid if 0 <= pid <= MAX_PEER_ID else None

    def owns_table(self, table: int) -> bool:
        return self.table_base <= table <= self.table_base + MAX_PEER_ID


# --------------------------------------------------------------------------
# Command helpers
# --------------------------------------------------------------------------


def run(cmd: list[str]) -> subprocess.CompletedProcess:
    """Run a command, never raising (callers decide what a failure means)."""
    try:
        return subprocess.run(cmd, capture_output=True, text=True, check=False)
    except OSError as exc:  # e.g. the binary isn't on PATH
        return subprocess.CompletedProcess(cmd, 127, "", str(exc))


def run_ok(cmd: list[str], what: str) -> bool:
    res = run(cmd)
    if res.returncode != 0:
        log.error("%s failed (%s): %s", what, " ".join(cmd), res.stderr.strip())
        return False
    return True


def run_json(cmd: list[str]):
    res = run(cmd)
    if res.returncode != 0:
        log.error("%s failed: %s", " ".join(cmd), res.stderr.strip())
        return None
    try:
        return json.loads(res.stdout or "[]")
    except json.JSONDecodeError as exc:
        log.error("%s: bad JSON: %s", " ".join(cmd), exc)
        return None


# --------------------------------------------------------------------------
# Per-tun state: policy routing + nft pinning
# --------------------------------------------------------------------------


def parse_rules(rules) -> set[int]:
    """Tables T that have an `fwmark T lookup T` rule."""
    found: set[int] = set()
    for r in rules or []:
        try:
            table = int(r.get("table", ""))
            mark = int(r.get("fwmark", "0"), 16)
        except ValueError:
            continue
        if mark == table:
            found.add(table)
    return found


def rule_tables(cfg: Config) -> set[int]:
    rules = run_json(["ip", "-4", "-j", "rule", "show"])
    return {t for t in parse_rules(rules) if cfg.owns_table(t)}


def ensure_rule(table: int, have: set[int] | None = None) -> None:
    """Add `fwmark T lookup T` unless present. `have` is a cached listing."""
    if have is None:
        have = parse_rules(run_json(["ip", "-4", "-j", "rule", "show"]))
    if table in have:
        return
    # pref 0: must be evaluated before `local` (uplink.nix moves local to pref 1
    # to make room). Without an explicit pref the kernel picks ~32765, after it.
    run_ok(["ip", "-4", "rule", "add", "pref", "0", "fwmark", str(table), "table", str(table)],
           f"add rule for table {table}")


def ensure_route(table: int, ifname: str) -> None:
    run_ok(["ip", "-4", "route", "replace", "default", "dev", ifname, "table", str(table),
            "proto", ROUTE_PROTO],
           f"default route via {ifname} in table {table}")


def nft_elems(cfg: Config, kind: str, name: str) -> list | None:
    """Elements of a named set/map, or None if it can't be read."""
    data = run_json(["nft", "-j", "list", kind, cfg.nft_family, cfg.nft_table, name])
    if data is None:
        return None
    for item in data.get("nftables", []):
        if kind in item:
            return item[kind].get("elem", [])
    return []


def nft_state(cfg: Config) -> tuple[set[int], dict[str, int]] | None:
    marks = nft_elems(cfg, "set", cfg.nft_mark_set)
    ifaces = nft_elems(cfg, "map", cfg.nft_iface_map)
    if marks is None or ifaces is None:
        return None
    mark_set = {m for m in marks if isinstance(m, int)}
    iface_map = {e[0]: e[1] for e in ifaces
                 if isinstance(e, list) and len(e) == 2 and isinstance(e[0], str) and isinstance(e[1], int)}
    return mark_set, iface_map


def nft_add(cfg: Config, peers: dict[int, str]) -> None:
    if not peers:
        return
    marks = ", ".join(str(cfg.table(p)) for p in sorted(peers))
    pairs = ", ".join(f'"{peers[p]}" : {cfg.table(p)}' for p in sorted(peers))
    base = ["nft", "add", "element", cfg.nft_family, cfg.nft_table]
    run_ok(base + [cfg.nft_mark_set, "{ " + marks + " }"], "register peer marks with nftables")
    run_ok(base + [cfg.nft_iface_map, "{ " + pairs + " }"], "register peer ifaces with nftables")


def nft_delete(cfg: Config, marks: list[int], ifnames: list[str]) -> None:
    base = ["nft", "delete", "element", cfg.nft_family, cfg.nft_table]
    if ifnames:
        keys = ", ".join(f'"{n}"' for n in ifnames)
        run_ok(base + [cfg.nft_iface_map, "{ " + keys + " }"], "deregister peer ifaces from nftables")
    if marks:
        run_ok(base + [cfg.nft_mark_set, "{ " + ", ".join(map(str, marks)) + " }"],
               "deregister peer marks from nftables")


def setup_peer(cfg: Config, peer_id: int, ifname: str) -> None:
    table = cfg.table(peer_id)
    ensure_rule(table)
    ensure_route(table, ifname)
    nft_add(cfg, {peer_id: ifname})
    log.info("set up peer %d (%s): table/mark %d", peer_id, ifname, table)


def teardown_peer(cfg: Config, peer_id: int, ifname: str) -> None:
    table = cfg.table(peer_id)
    # Remove every matching rule (there should only be one, but be thorough).
    for _ in range(8):
        if run(["ip", "-4", "rule", "del", "fwmark", str(table), "table", str(table)]).returncode != 0:
            break
    run(["ip", "-4", "route", "flush", "table", str(table)])
    nft_delete_quiet(cfg, [table], [ifname])
    log.info("tore down peer %d (%s): table/mark %d", peer_id, ifname, table)


def nft_delete_quiet(cfg: Config, marks: list[int], ifnames: list[str]) -> None:
    # Elements may already be gone (e.g. nftables was reloaded); that's fine.
    base = ["nft", "delete", "element", cfg.nft_family, cfg.nft_table]
    for n in ifnames:
        run(base + [cfg.nft_iface_map, '{ "%s" }' % n])
    for m in marks:
        run(base + [cfg.nft_mark_set, "{ %d }" % m])


def live_tuns(cfg: Config) -> dict[int, tuple[str, int]] | None:
    """peer id -> (ifname, ifindex) for every existing `<tun_prefix><id>`."""
    links = run_json(["ip", "-j", "link", "show"])
    if links is None:
        return None
    out: dict[int, tuple[str, int]] = {}
    for link in links:
        name = link.get("ifname", "")
        pid = cfg.peer_id_of(name)
        if pid is not None:
            out[pid] = (name, int(link.get("ifindex", 0)))
    return out


def full_reconcile(cfg: Config, live: dict[int, tuple[str, int]]) -> None:
    """Make rules/routes/nft exactly match the set of live tuns."""
    have_rules = rule_tables(cfg)
    for pid, (name, _idx) in live.items():
        table = cfg.table(pid)
        ensure_rule(table, have_rules)
        ensure_route(table, name)

    # Garbage-collect state for tuns that no longer exist.
    live_tables = {cfg.table(p) for p in live}
    for table in sorted(have_rules - live_tables):
        log.info("gc: stale rule/routes for table %d", table)
        run(["ip", "-4", "rule", "del", "fwmark", str(table), "table", str(table)])
        run(["ip", "-4", "route", "flush", "table", str(table)])

    state = nft_state(cfg)
    if state is None:
        return  # nft table not there (yet); try again next resync
    cur_marks, cur_map = state
    want_marks = live_tables
    want_map = {name: cfg.table(pid) for pid, (name, _idx) in live.items()}

    stale_names = [n for n, m in cur_map.items()
                   if cfg.peer_id_of(n) is not None and (want_map.get(n) != m)]
    stale_marks = [m for m in cur_marks if cfg.owns_table(m) and m not in want_marks]
    if stale_names or stale_marks:
        nft_delete(cfg, stale_marks, stale_names)

    missing = {pid: name for pid, (name, _idx) in live.items()
               if cfg.table(pid) not in cur_marks or cur_map.get(name) != cfg.table(pid)}
    if missing:
        log.info("nft: (re)registering peers %s", sorted(missing))
        nft_add(cfg, missing)


# --------------------------------------------------------------------------
# Prefix advertisement
# --------------------------------------------------------------------------


def normalize_prefix(val: str) -> str | None:
    """`1.2.3.4` -> `1.2.3.4/32`, host bits masked; None if not IPv4."""
    try:
        net = ipaddress.ip_network(val.strip(), strict=False)
    except ValueError:
        return None
    if net.version != 4:
        return None
    return str(net)


def vm_routes(cfg: Config) -> set[str] | None:
    if not cfg.vm_ifaces:
        return set()
    routes = run_json(["ip", "-4", "-j", "route", "show"])
    if routes is None:
        return None
    out: set[str] = set()
    vm = set(cfg.vm_ifaces)
    for r in routes:
        dst = r.get("dst")
        if not dst or dst == "default" or r.get("dev") not in vm:
            continue
        norm = normalize_prefix(dst)
        if norm:
            out.add(norm)
    return out


def desired_prefixes(cfg: Config) -> set[str] | None:
    vms = vm_routes(cfg)
    if vms is None:
        return None  # keep what we have advertised rather than flap on a read error
    out = set(vms)
    for p in [*cfg.pub_ips, *cfg.extra_routes]:
        norm = normalize_prefix(p)
        if norm:
            out.add(norm)
        else:
            log.warning("ignoring invalid configured prefix %r", p)
    return out


class UnixHTTPConnection(http.client.HTTPConnection):
    def __init__(self, path: str, timeout: float = 5.0):
        super().__init__("localhost", timeout=timeout)
        self._path = path

    def connect(self) -> None:
        sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        sock.settimeout(self.timeout)
        sock.connect(self._path)
        self.sock = sock


def control_post(socket_path: str, endpoint: str, prefix: str) -> bool:
    conn = UnixHTTPConnection(socket_path)
    try:
        conn.request("POST", endpoint, body=json.dumps({"prefix": prefix}),
                     headers={"Content-Type": "application/json"})
        resp = conn.getresponse()
        body = resp.read().decode(errors="replace").strip()
        if resp.status != 200:
            log.error("control API %s %s -> %d: %s", endpoint, prefix, resp.status, body)
            return False
        return True
    except OSError as exc:
        log.warning("control API %s %s: %s", endpoint, prefix, exc)
        return False
    finally:
        conn.close()


@dataclass
class AdvertState:
    advertised: set[str] = field(default_factory=set)
    sock_ident: tuple[int, int] | None = None


def sync_advertisements(cfg: Config, state: AdvertState, desired: set[str]) -> None:
    try:
        st = os.stat(cfg.control_socket)
    except OSError:
        # melnode isn't up (or is restarting): whatever it knew is gone.
        state.advertised.clear()
        state.sock_ident = None
        return

    # A new socket file means melnode restarted and lost its local prefixes.
    ident = (st.st_ino, st.st_mtime_ns)
    if ident != state.sock_ident:
        if state.sock_ident is not None:
            log.info("control socket was recreated; re-advertising everything")
        state.advertised.clear()
        state.sock_ident = ident

    for prefix in sorted(desired - state.advertised):
        if not control_post(cfg.control_socket, "/advertise", prefix):
            return
        state.advertised.add(prefix)
        log.info("advertised %s", prefix)
    for prefix in sorted(state.advertised - desired):
        if not control_post(cfg.control_socket, "/withdraw", prefix):
            return
        state.advertised.discard(prefix)
        log.info("withdrew %s", prefix)


# --------------------------------------------------------------------------
# Daemon
# --------------------------------------------------------------------------


def daemon(cfg: Config) -> int:
    stop = threading.Event()
    signal.signal(signal.SIGTERM, lambda *_: stop.set())
    signal.signal(signal.SIGINT, lambda *_: stop.set())

    state = AdvertState()
    known: dict[int, tuple[str, int]] = {}
    tick = 0
    log.info("daemon started (node %d, control socket %s)", cfg.node_id, cfg.control_socket)

    while not stop.is_set():
        try:
            live = live_tuns(cfg)
            if live is not None:
                # Reconcile immediately when a tun appears/changes/vanishes, and
                # periodically regardless (heals e.g. an nftables reload).
                if live != known or tick % cfg.full_resync_ticks == 0:
                    full_reconcile(cfg, live)
                known = live

            desired = desired_prefixes(cfg)
            if desired is not None:
                sync_advertisements(cfg, state, desired)
        except Exception:  # never let one bad tick kill the daemon
            log.exception("tick failed")
        tick += 1
        stop.wait(cfg.poll_interval)

    # Deliberately no withdrawal on shutdown: the helper restarts on every
    # deploy that touches its config, and withdrawing first would pull this
    # node's prefixes from the whole mesh for a tick. The next helper
    # re-advertises idempotently; if melnode-cp restarts instead, it starts
    # with an empty local set anyway.
    log.info("daemon stopped")
    return 0


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--config", required=True, help="path to the JSON config generated by melinoe-vpn.nix")
    sub = ap.add_subparsers(dest="cmd", required=True)
    for name in ("hook-create", "hook-destroy"):
        p = sub.add_parser(name)
        p.add_argument("peer_id", type=int)
        p.add_argument("ifname")
    sub.add_parser("daemon")
    args = ap.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(name)s: %(message)s", stream=sys.stderr)
    cfg = Config.load(args.config)

    if args.cmd in ("hook-create", "hook-destroy"):
        if not 0 <= args.peer_id <= MAX_PEER_ID:
            log.error("peer id %d out of range", args.peer_id)
            return 2
        (setup_peer if args.cmd == "hook-create" else teardown_peer)(cfg, args.peer_id, args.ifname)
        return 0
    return daemon(cfg)


if __name__ == "__main__":
    sys.exit(main())
